search_term: '"Ai engineer" OR "Machine learning engineer" OR "Data scientist"'
results_wanted: 30
hours_old: 100
linkedin_fetch_description: true
description_format: markdown

site_name:
  - linkedin
  - indeed
  # - bayt  # Disabled - no longer used
  # - google  # Disabled - no longer used

locations:
  # Egypt
  - Cairo, Egypt
  - Giza, Egypt
  - New Cairo, Egypt
  - 6th of October City, Egypt
  - Nasr City, Egypt
  - Sheikh Zayed City, Egypt
  # UAE
  - Dubai, UAE
  - Abu Dhabi, UAE
  - Sharjah, UAE
  - Al Ain, UAE
  # Saudi Arabia
  - Riyadh, Saudi Arabia
  - Jeddah, Saudi Arabia
  - Dammam, Saudi Arabia
  - Khobar, Saudi Arabia
  - Mecca, Saudi Arabia
  - Medina, Saudi Arabia
  - NEOM, Saudi Arabia
  # Kuwait
  - Kuwait City, Kuwait
  - Hawally, Kuwait
  - Salmiya, Kuwait
  # Qatar, Oman, Bahrain
  - Doha, Qatar
  - Muscat, Oman
  - Manama, Bahrain
  # Germany
  - Berlin, Germany
  - Munich, Germany
  - Frankfurt, Germany
  - Hamburg, Germany
  - Stuttgart, Germany
  # Spain
  - Madrid, Spain
  - Barcelona, Spain
  - Valencia, Spain
  # UK
  - London, UK
  - Manchester, UK
  - Cambridge, UK
  - Edinburgh, UK
  - Birmingham, UK
  - Bristol, UK
  - Nottingham, UK
  - Glasgow, UK
  - Aberdeen, UK
  - Dundee, UK
  # Ireland
  - Dublin, Ireland
  - Cork, Ireland
  - Galway, Ireland
  - Limerick, Ireland
  # Austria
  - Vienna, Austria
  - Linz, Austria
  - Graz, Austria
  # Canada
  - Toronto, Canada
  - Vancouver, Canada
  - Montreal, Canada
  - Ottawa, Canada
  - Calgary, Canada
  - Edmonton, Canada
  - Waterloo, Canada
  # Australia
  - Sydney, Australia
  - Melbourne, Australia
  - Brisbane, Australia
  - Perth, Australia
  - Adelaide, Australia
  - Canberra, Australia
  - Gold Coast, Australia
  # New Zealand
  - Auckland, New Zealand
  - Wellington, New Zealand
  - Christchurch, New Zealand
  - Hamilton, New Zealand
  - Tauranga, New Zealand
  
use_llm_filter: true
llm_prompt_template: |
  You are a job relevance filter AI. Check if the following job is relevant to the search: {search_term} and not for seniors.
  Title: {title}
  Company: {company}
  Location: {location}
  Description: {description}
  Is this job related? Respond with only 'yes' or 'no'.

llm_model: mistralai/mistral-small-3.2-24b-instruct:free

llm_use_local: true
llm_local_model_path: /media/hossam/NewVolume/job_scrape/jobspy_project_clean/JobSpy/job_filter_app/ollama_models
llm_local_model_name: mistral:latest  # The name as used by Ollama

# GPU and Performance Optimization Settings
use_gpu: true                    # Enable GPU acceleration
gpu_layers: 10                   # Number of GPU layers (reduced for safety)
max_consecutive_jobs: 2          # Process 5 jobs then check system health
break_duration: 60               # Seconds to wait when system overheats
cpu_threshold: 65                # CPU temperature threshold in Celsius
memory_threshold: 70             # Memory usage threshold in percentage

output_dir: filtered_jobs
export_csv: true
export_html: true

#proxies:
  #- qqxegrku:u6msqzeehxwh@198.23.239.134:6540
  #- qqxegrku:u6msqzeehxwh@207.244.217.165:6712
  #- qqxegrku:u6msqzeehxwh@107.172.163.27:6543
  #- qqxegrku:u6msqzeehxwh@23.94.138.75:6349
  #- qqxegrku:u6msqzeehxwh@216.10.27.159:6837
  #- qqxegrku:u6msqzeehxwh@136.0.207.84:6661
  #- qqxegrku:u6msqzeehxwh@64.64.118.149:6732
  #- qqxegrku:u6msqzeehxwh@142.147.128.93:6593
  #- qqxegrku:u6msqzeehxwh@104.239.105.125:6655
  #- qqxegrku:u6msqzeehxwh@173.0.9.70:5653
  #- localhost

# Output file configuration
output_file: data/jobs_raw.csv

